### ISSUE TITLE
Is HEALTHCHECK really necessary?

### ISSUE THREAD

**Issue by inductor** [goodwithtech/dockle#10]
In the [Docker Best practices document](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/), I could not find any instructions about `HEALTHCHECK`.

I understand how it works and I know it is useful in some ways, but I don't think it is "essential".

I think WARNING would be good instead of FATAL.

In what point did you define the classification? :)

**Comment by KEINOS** [comment]
> I think WARNING would be good instead of FATAL.

I agree with @inductor. 

I found an instruction about the `HEALTHCHECK` in [CIS' download document](https://learn.cisecurity.org/benchmarks) of "Docker Community Edition Benchmark"(v1.1.0, P.123). Which I believe [`Dockle` is based on](https://qiita.com/tomoyamachi/items/bb6ac5788bb734c91282#%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%99%E3%82%8B%E9%A0%85%E7%9B%AE). 

According to CIS' instructions, `HEALTHCHECK` should be scored, though the **Impact** is "none".

So since this is not critical, I'll give a 👍for `WARN` to `HEALTHCHECK`.

Here's the brief quote extracted from section 4.6.

>  ### 4.6 Ensure HEALTHCHECK instructions have been added to the container image (Scored)
> #### Profile Applicability:
> - Level 1 - Docker
> #### Description:
> Add HEALTHCHECK instruction in your docker container images to perform the health check
on running containers.
> #### Rationale:
> One of the important security triads is availability. Adding HEALTHCHECK instruction to your
container image ensures that the docker engine periodically checks the running container
instances against that instruction to ensure that the instances are still working.
Based on the reported health status, the docker engine could then exit non-working
containers and instantiate new ones.
> #### Audit:
> Run the below command and ensure that the docker image has appropriate HEALTHCHECK
instruction set up.
> ```
> docker inspect --format='{{ .Config.Healthcheck }}' <IMAGE>
> ```
> #### Remediation:
> Follow Docker documentation and rebuild your container image with HEALTHCHECK instruction.
> #### Impact:
> None.
> #### Default Value:
> By default, HEALTHCHECK is not set.
> #### References:
> 1. https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by KEINOS** [comment]
Maybe like so?

https://github.com/goodwithtech/dockle/blob/559fde0c41f6a842235bc4a3bbd16594aa4a0542/pkg/types/checkpoint.go#L62-L66

```diff
- 	DefaultLevel: FatalLevel, 
+ 	DefaultLevel: WarnLevel, 
```

**Comment by tomoyamachi** [comment]
Same as #16.

I changed to WARN level.
Thanks!
