### ISSUE TITLE
Missing releases after v0.4.2?

### ISSUE THREAD

**Issue by erzz** [goodwithtech/dockle#179]
**Description**

Since v0.4.2 I notice you have only been creating tags, but not releases.  I have an [action](https://github.com/erzz/dockle-action/issues/15) that depended on those releases for determining latest version.

```bash
if [ "$DOCKLE_VERSION" = "latest" ]; then
    export DOCKLE_VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
fi
```

Just wondering what your plan is really - whether I should depend on release or tags? Perhaps there is a specific reason why 0.4.3-0.4.5 have not been released?

**Comment by tomoyamachi** [comment]
@erzz 
The Dockle repository is automated so that a release build is created when a tagged, so you can depend on tags.
I also make sure after each release that the release build can actually be downloaded and run.

0.4.3-0.4.5 builds are available from this page. 
https://github.com/goodwithtech/dockle/releases

**Comment by erzz** [comment]
Yeah, there was a week or two though where those latest 2 releases were missing. That seems to be rectified since so I ll close this. 

Thanks for the great work!
