### ISSUE TITLE
Add skip latest tag check option

### ISSUE THREAD

**Issue by inductor** [goodwithtech/dockle#19]
When you just want to quickly check if the latest version of this docker image is valid, it should be able to skip the latest tag check in some use cases.

it probably goes something like this :)

`dockle hoge/fuga:latest --ignore-latest`

**Comment by tomoyamachi** [comment]
You can use `.dockleignore`.
https://github.com/goodwithtech/dockle#ignore-the-specified-checkpoints

How about it?

**Comment by KEINOS** [comment]
I would like to have that option feature too.

Yes, `.dockleignore` would be an option. But in my case, most of my images on Docker Hub, I tag them when it becomes kinda stable, and `latest` is the latest merge since I use an automated build of Docker Cloud.

So ignore-option would be useful for **quick check** rather than placing `.dockleignore` on and off for every check.

**Comment by KEINOS** [comment]
Using `dockle` for a couple of days and thinking twice, I feel that **I won't need this ignore-option feature**. Sorry for flipping my opinion.


Since the results fulfill what I need to do, as a quick check, and using `.dockleignore` can be ignored the checks as a specification.

**Comment by tomoyamachi** [comment]
@inductor Oh, sorry. I will give options `--ignore CODE`, but please wait a while.

**Comment by tomoyamachi** [comment]
@inductor Dockle supports `--ignore, -i` option.
You can ignore latest tag to `dockle -i DKL-DI-0006 [IMAGE]`.
Please run v0.1.2.
