### ISSUE TITLE
Support Linuxbrew

### ISSUE THREAD

**Issue by inductor** [goodwithtech/dockle#9]
As homebrew now supports Linux environment, it'd be better to distribute linux bin on brew as well ._.

**Comment by KEINOS** [comment]
I think it's a good idea.

To ease installation, the PM (package manager) is very helpful.

But providing Dockle via each distro's common PM, such as `apk` `yum` `apt` etc., updating all of them on each release would be a pain, I imagine.

Since Homebrew on Linux also supports WSL (Windows Subsystem for Linux) and most of the binary for Linux are compiled already in the [releases page](https://github.com/goodwithtech/dockle/releases), I give a **👍for providing Dockle via PM for Linux in a single location such as `linuxbrew`**.

The problem is, I don't know much about `linuxbrew`'s formula or the cookbook to PR this.

**Comment by tomoyamachi** [comment]
supported!
